ARG BASE_IMAGE_REGISTRY=docker.io/cypress/
ARG BASE_IMAGE_NAME=included

# The Cypress version must match the version used in applications
# (e.g. "package.json" under "dependencies.cypress").
# If the "cypress" version specified in "package.json" is "latest",
# it will still use a specific version in "yarn.lock", so it is best
# practice to always specify a specific version.
ARG CYPRESS_VERSION=12.7.0
ARG NODE_VERSION=18.14.1
ARG CHROME_VERSION=110.0.5481.96-1-ff-109.0
ARG EDGE_VERSION=110.0.1587.41-1

ARG BASE_IMAGE_PATH=${BASE_IMAGE_REGISTRY}${BASE_IMAGE_NAME}:cypress-${CYPRESS_VERSION}-node-${NODE_VERSION}-chrome-${CHROME_VERSION}-edge-${EDGE_VERSION}

FROM ${BASE_IMAGE_PATH} as base

LABEL org.opencontainers.image.source=https://github.com/ourchitecture/fidlit
LABEL org.opencontainers.image.description="The latest node + Cypress testing + chrome installation"
