ARG BASE_IMAGE_REGISTRY=docker.io/zenika/
ARG BASE_IMAGE_NAME=alpine-chrome
ARG BASE_IMAGE_TAG=100-with-node

ARG BASE_IMAGE_PATH=${BASE_IMAGE_REGISTRY}${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

ARG PNPM_VERSION=8.1.1

FROM ${BASE_IMAGE_PATH} as base

ARG PNPM_VERSION

# Switch to root to update dependencies.
USER root

# The base container node version is behind latest, long-term support.
# Remove and reinstall all node packages due to dependencies.
RUN apk update \
    && apk del \
      nodejs \
      nodejs-npm \
      npm \
      yarn \
    && apk upgrade \
      --available \
      --no-cache \
    && apk add \
      nodejs \
      nodejs-npm \
      npm \
      yarn

# Install pnpm.
RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" PNPM_VERSION=${PNPM_VERSION} sh -

USER chrome

LABEL org.opencontainers.image.source=https://github.com/ourchitecture/fidlit
LABEL org.opencontainers.image.description="The latest node + chrome installation"
