ARG BASE_IMAGE_REGISTRY=docker.io/zenika/
ARG BASE_IMAGE_NAME=alpine-chrome

# The base version of Chromium will likely be updated to latest with `apk update`.
ARG BASE_IMAGE_TAG=108-with-node

ARG BASE_IMAGE_PATH=${BASE_IMAGE_REGISTRY}${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

FROM ${BASE_IMAGE_PATH} as base

ARG PNPM_VERSION=8.1.1

# Switch to root to update dependencies.
USER root

# The base container node version is behind latest, long-term support.
# Remove and reinstall all node packages due to dependencies.
RUN apk update \
    && apk del \
      nodejs \
      npm \
      yarn \
    && apk upgrade \
      --available \
      --no-cache \
    && apk add \
      nodejs \
      npm \
      yarn

# Install pnpm.
RUN npm install --location=global pnpm@${PNPM_VERSION}

USER chrome

LABEL org.opencontainers.image.source=https://github.com/ourchitecture/fidlit
LABEL org.opencontainers.image.description="The latest node + chrome installation"
