################################################################################
# Installs and Deploys the node container as a GitHub package.
################################################################################
name: containers_node_cd

on:
  push:
    branches: [main]
    paths:
      # run this build when this file changes
      - ".github/workflows/containers_node_cd.yaml"
      # run this build when the source code changes
      - "src/containers/node/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CI: 1

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: ./src/containers/node/

    steps:
      - uses: actions/checkout@v2

      - name: login
        env:
          CONTAINER_USERNAME: ${{ secrets.FIDLIT_GITHUB_PACKAGES_CONTAINER_USERNAME }}
          CONTAINER_PASSWORD: ${{ secrets.FIDLIT_GITHUB_PACKAGES_CONTAINER_TOKEN }}
        run: |
          echo "${{ env.CONTAINER_PASSWORD }}" > ./CONTAINER_PASSWORD
          make login-ghcr username="${{ env.CONTAINER_USERNAME }}" ghcr_token_file_path=./CONTAINER_PASSWORD

      - name: install
        working-directory: ${{env.PROJECT_PATH}}
        run: |
          find . -type f -iname "*.sh" -exec chmod +x {} \;
          make all
          make deploy
