################################################################################
# Installs and Deploys the node-chrome container as a GitHub package.
################################################################################
name: containers_node-chrome_ci

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      # Run this build when this file changes.
      - ".github/workflows/containers_node-chrome_ci.yaml"
      # Run this build when the source code changes.
      - "src/containers/node-chrome/**"

env:
  CI: 1

jobs:
  integrate:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: ./src/containers/node-chrome/

    steps:
      - uses: actions/checkout@v3

      - name: install
        working-directory: ${{env.PROJECT_PATH}}
        run: |
          find . -type f -iname "*.sh" -exec chmod +x {} \;
          make all
