################################################################################
# Installs and Deploys the node container as a GitHub package.
################################################################################
name: containers_node_ci

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      # Run this build when this file changes.
      - ".github/workflows/containers_node_ci.yaml"
      # Run this build when the source code changes.
      - "src/containers/node/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CI: 1

jobs:
  integrate:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: ./src/containers/node/

    steps:
      - uses: actions/checkout@v3

      - name: install
        working-directory: ${{env.PROJECT_PATH}}
        run: |
          find . -type f -iname "*.sh" -exec chmod +x {} \;
          make all
